"""add telegram fields to users

Revision ID: 24ab610c041b
Revises: 37a4e49cb5cd
Create Date: 2026-02-21 23:20:11.612737

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '24ab610c041b'
down_revision: Union[str, None] = '37a4e49cb5cd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('otp_channel', sa.String(16), nullable=False, server_default='email'))
    op.add_column('users', sa.Column('telegram_chat_id', sa.String(length=64), nullable=True))
    op.add_column('users', sa.Column('telegram_confirmed', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'telegram_confirmed')
    op.drop_column('users', 'telegram_chat_id')
    op.drop_column('users', 'otp_channel')
    # ### end Alembic commands ###
