"""create all tables

Revision ID: 37a4e49cb5cd
Revises: 
Create Date: 2026-02-21 15:27:42.843396

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '37a4e49cb5cd'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kpi_indicators',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name_display', sa.String(length=255), nullable=False),
    sa.Column('name_system', sa.String(length=128), nullable=False),
    sa.Column('value_type', sa.Enum('NUMBER', 'PERCENT', 'BOOLEAN', 'TIME', name='valuetype'), nullable=False),
    sa.Column('source_type', sa.Enum('REST_API', 'DATABASE', 'CSV', 'XLSX', 'WEBHOOK', 'MANUAL', 'COMPUTED', name='sourcetype'), nullable=False),
    sa.Column('formula', sa.Text(), nullable=True),
    sa.Column('cron_schedule', sa.String(length=64), nullable=True),
    sa.Column('last_run_at', sa.DateTime(), nullable=True),
    sa.Column('last_run_status', sa.String(length=32), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name_system')
    )
    op.create_index(op.f('ix_kpi_indicators_id'), 'kpi_indicators', ['id'], unique=False)
    op.create_table('link_sections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('icon', sa.String(length=255), nullable=True),
    sa.Column('order', sa.Integer(), nullable=True),
    sa.Column('is_global', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_link_sections_id'), 'link_sections', ['id'], unique=False)
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('icon', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_roles_id'), 'roles', ['id'], unique=False)
    op.create_table('kpi_data_sources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('indicator_id', sa.Integer(), nullable=False),
    sa.Column('api_url', sa.String(length=512), nullable=True),
    sa.Column('api_method', sa.String(length=8), nullable=True),
    sa.Column('api_auth_type', sa.String(length=32), nullable=True),
    sa.Column('api_auth_value', sa.Text(), nullable=True),
    sa.Column('db_connection_string', sa.Text(), nullable=True),
    sa.Column('db_query', sa.Text(), nullable=True),
    sa.Column('sftp_host', sa.String(length=255), nullable=True),
    sa.Column('sftp_path', sa.String(length=512), nullable=True),
    sa.Column('sftp_credentials', sa.Text(), nullable=True),
    sa.Column('extra_config', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['indicator_id'], ['kpi_indicators.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('indicator_id')
    )
    op.create_table('links',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('section_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('url', sa.String(length=1024), nullable=False),
    sa.Column('icon', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('open_in_iframe', sa.Boolean(), nullable=True),
    sa.Column('order', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['section_id'], ['link_sections.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_links_id'), 'links', ['id'], unique=False)
    op.create_table('role_indicators',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('indicator_id', sa.Integer(), nullable=False),
    sa.Column('weight', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['indicator_id'], ['kpi_indicators.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('role_link_sections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('section_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.ForeignKeyConstraint(['section_id'], ['link_sections.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('continent', sa.String(length=64), nullable=True),
    sa.Column('country', sa.String(length=64), nullable=True),
    sa.Column('city', sa.String(length=128), nullable=True),
    sa.Column('role', sa.Enum('EMPLOYEE', 'MANAGER', 'ADMIN', name='userrole'), nullable=False),
    sa.Column('access_level', sa.Enum('GLOBAL', 'CONTINENTAL', 'COUNTRY', 'INDUSTRY', 'CITY', name='accesslevel'), nullable=True),
    sa.Column('scope_value', sa.String(length=255), nullable=True),
    sa.Column('manager_id', sa.Integer(), nullable=True),
    sa.Column('portal_role_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('can_edit_links', sa.Boolean(), nullable=True),
    sa.Column('can_edit_kpi', sa.Boolean(), nullable=True),
    sa.Column('can_set_plan', sa.Boolean(), nullable=True),
    sa.Column('can_adjust_kpi', sa.Boolean(), nullable=True),
    sa.Column('kpi_adjust_limit_pct', sa.Integer(), nullable=True),
    sa.Column('can_manage_team', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['manager_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['portal_role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=128), nullable=False),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('method', sa.String(length=32), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=True),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('kpi_targets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('indicator_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('target_value', sa.Float(), nullable=False),
    sa.Column('set_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['indicator_id'], ['kpi_indicators.id'], ),
    sa.ForeignKeyConstraint(['set_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('kpi_values',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('indicator_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('adjusted_by_id', sa.Integer(), nullable=True),
    sa.Column('adjusted_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['adjusted_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['indicator_id'], ['kpi_indicators.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('kpi_values')
    op.drop_table('kpi_targets')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('role_link_sections')
    op.drop_table('role_indicators')
    op.drop_index(op.f('ix_links_id'), table_name='links')
    op.drop_table('links')
    op.drop_table('kpi_data_sources')
    op.drop_index(op.f('ix_roles_id'), table_name='roles')
    op.drop_table('roles')
    op.drop_index(op.f('ix_link_sections_id'), table_name='link_sections')
    op.drop_table('link_sections')
    op.drop_index(op.f('ix_kpi_indicators_id'), table_name='kpi_indicators')
    op.drop_table('kpi_indicators')
    # ### end Alembic commands ###
